apiVersion: apps/v1
kind: Deployment
metadata:
  name: aesop-vue-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aesop-vue
  template:
    metadata:
      labels:
        app: aesop-vue
    spec:
      containers:
      - name: aesop-vue
        image: aesop-vue
        imagePullPolicy: Never
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "256Mi"
            cpu: "1000m"
        ports:
        - containerPort: 80
