apiVersion: apps/v1
kind: Deployment
metadata:
  name: aesop-api-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aesop-api
  template:
    metadata:
      labels:
        app: aesop-api
    spec:
      containers:
      - name: aesop-api
        image: aesopwow-api
        imagePullPolicy: Never
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "256Mi"
            cpu: "1000m"
        ports:
        - containerPort: 8091
        # 컨테이너 안의 애플리케이션이 시작되었는지 확인한다.
        # startupProbe:
        #   httpGet:
        #     path: /actuator/health
        #     port: 8091
        #   # 실패를 허용하는 최대 횟수
        #   failureThreshold: 10
        #   # 10초마다 상태를 확인
        #   periodSeconds: 10
        # # 컨테이너 안의 애플리케이션이 살아있는지 지속적으로 확인한다.
        # livenessProbe:
        #   httpGet:
        #     path: /actuator/health/liveness
        #     port: 8091
        #   initialDelaySeconds: 10
        #   periodSeconds: 20
        # # 컨테이너 안의 애플리케이션이 실제로 서비스 요청에 응답할 수 있는지 확인한다.
        # readinessProbe:
        #   httpGet:
        #     path: /actuator/health/readiness
        #     port: 8091
        #   initialDelaySeconds: 5
        #   periodSeconds: 5